### ISSUE TITLE
sending soul to other adress: fail

### ISSUE THREAD

**Issue by TGW69** [phantasma-io/Poltergeist#54]
When you want to send soul to another address the qr function fails and crashes the wallet. Also you cannot paste an address. But who wants to manually fill out a sent address with so many characters... that is a fail!

**Comment by alexmpa** [comment]
Please provide details on your issue. QR function works well for me and many other users, and paste of the address is supported of course, I'm using it all the time. What device and OS are you using? Can you please provide poltergeist.log after reproducing an error?

Log can be found here:
1) For Android: /storage/emulated/0/Android/data/com.Phantasma.PoltergeistWallet/files/poltegeist.log
2) For Windows: C:\Users\*UserName*\AppData\LocalLow\Phantasma\Poltergeist Wallet\poltegeist.log
3) For MacOS: /Users/*UserName*/Library/Application Support/com.Phantasma.PoltergeistWallet/poltegeist.log

**Comment by TGW69** [comment]
Hi, thanks for reaching out. I run Poltergeist 2.1.1 on an imac with
cataline ios version 10.15.7
when I try to use the qr function I get a fail: part of log shown below
Process:               Poltergeist Wallet [75723]
Path:
 /private/var/folders/*/Poltergeist.app/Contents/MacOS/Poltergeist Wallet
Identifier:            com.Company.ProductName
Version:               2.1.1 (0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Poltergeist Wallet [75723]
User ID:               501

Date/Time:             2021-02-10 20:32:35.276 +0100
OS Version:            Mac OS X 10.15.7 (19H114)
Report Version:        12
Anonymous UUID:        B6FEC5B6-A6B9-619D-68C0-AF1117BB9046

Sleep/Wake UUID:       724E6B5E-6F38-48F4-8D33-0D4E1EB292FD

Time Awake Since Boot: 520000 seconds
Time Since Wake:       23000 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        3  Dispatch queue: com.apple.root.default-qos

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
and i cannot use the paste function. What to do?
Tj


Op wo 10 feb. 2021 om 19:35 schreef alexmpa <notifications@github.com>:

**Comment by alexmpa** [comment]
Thank you for a detailed answer! We will publish a new version soon that will hopefully resolve your camera issue.

About paste function, can you please explain, how exactly are you trying to paste address in the wallet? Do you use keyboard keys combination or are you trying to open context menu on address input field?

**Comment by TGW69** [comment]
Hi, in the "soul" box of the window, I hit send. Normally I paste the
address from the right click mouse button. So I copy the address first from
ledger or metamask or a dep address of an exchange and than normally can
paste it but not here. nor does the top menu in the imax bar have a paste
function in the Poltergeist menu. What would be the function key to paste
then on an imac?

Op do 11 feb. 2021 om 00:11 schreef alexmpa <notifications@github.com>:

**Comment by TGW69** [comment]
Hi, with control v on the imac I can now paste. Still does not work with
right click mouse but ok I can now at least paste a sent address which is
great. Now leaves the qr function which crashes the app each time and on
which I sent you the log.
Tjeerd

Op do 11 feb. 2021 om 00:11 schreef alexmpa <notifications@github.com>:

**Comment by alexmpa** [comment]
Hi, yes, context menus on input fields are not supported, UI is designed that way. "Cmd"+"V" should always work. About camera - yes, will publish updated version later today.

**Comment by TGW69** [comment]
Ok, thank you.

Op do 11 feb. 2021 om 15:40 schreef alexmpa <notifications@github.com>:

**Comment by alexmpa** [comment]
Please try new release: https://github.com/phantasma-io/Poltergeist/releases/tag/v2.1.2

**Comment by TGW69** [comment]
It works now thanks!! Tjeerd

Op vr 12 feb. 2021 om 01:01 schreef alexmpa <notifications@github.com>:

**Comment by alexmpa** [comment]
Excellent! Thank you for reporting this issue!
