### ISSUE TITLE
Can't transfer GAS from Gate to NEO 3

### ISSUE THREAD

**Issue by kcsf** [phantasma-io/Poltergeist#58]
Transfer fails.
After further investigation, looks like Gate upgraded to Neo N3 Mainnet:
https://www.gate.io/en/article/22525/?ch=en_sm_0921

Now, I have no idea how to get GAS into poltergeist, in order to move SOUL from NEO to phantasma.
Please help.

**Comment by kcsf** [comment]
Thanks Relfos.
Will you please reply here when its ready?

**Comment by alexmpa** [comment]
Sure, also please contact admins on phantasma telegram channel https://t.me/phantasma_io
They will provide you with a drop of gas needed to swap SOUL to mainnet.

**Comment by kcsf** [comment]
4 months later - still, no support for NEO3.
I can't believe this.

**Comment by alexmpa** [comment]
Can't belive that we have huge queue of pending tasks and this one has lower priority than others?
