### ISSUE TITLE
OS X app not working on Ventura

### ISSUE THREAD

**Issue by danielschlegel** [phantasma-io/Poltergeist#68]
I download the latest version of Poltergeist for osx here: https://github.com/phantasma-io/Poltergeist/releases

When i try to open it i get: The application “Poltergeist” can’t be opened.

Also disabling Gatekeeper did not help.

**Comment by TeknoPT** [comment]
The version 2.8.2 should fix your issue.

The 2.8.3 is will be deployed tomorrow
